apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: buzzbingo-ui-v000
  namespace: buzzbingo
  labels:
    app: buzzbingo
    stack: ui
    version: v000
spec:
  replicas: 1
  selector:
      matchLabels:
        replication-controller: buzzbingo-ui-v000
  template:
    metadata:
      labels:
        replication-controller: buzzbingo-ui-v000
        load-balancer-buzzbingo-ui: "true"
    spec:
      containers:
      - image: emjburns/buzzbingo-ui:latest
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 3000
      restartPolicy: Always
