apiVersion: v1
kind: Service
metadata:
  name: buzzbingo-api
  namespace: buzzbingo
  labels:
    app: buzzbingo
    stack: api
spec:
  selector:
    load-balancer-buzzbingo-api: "true"
  type: LoadBalancer
  ports:
  - name: "api"
    port: 80
    targetPort: 8080
