apiVersion: v1
kind: Service
metadata:
  namespace: buzzbingo
  name: buzzbingo-redis
  labels:
    app: buzzbingo
    stack: redis
spec:
  ports:
  - name: "redis"
    port: 6379
    targetPort: 6379
  selector:
    load-balancer-buzzbingo-redis: "true"
